const db = require("./src/loaders/database.js")
const webserver = require("./src/loaders/webserver.js")
const frontEnd = require("./src/loaders/frontEnd.js")
const socketManager = require("./src/loaders/socketManager.js")
console.log("Running App!")
